<div class="breadcrumb-custom">
  <i class="fa fa-user"></i> Meus Dados
  <span class="location" style="float: right;">Home > Meus dados</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>
  
  <div class="col xs-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-warning"></i> Atenção!</h3>
      </div>
      <div class="panel-body text-center">
        Todos os campos com o <span style="color: red;">*</span> são obrigatórios.
      </div>
    </div>
  </div>    

  <div class="col-xs-12 col-sm-4">
    <div class="thumbnail text-center">
      <img src="" alt="" class="img-responsive" style="width: 30%; height: 30%; padding: 10px 0;">
      <button type="file" class="btn side-primary-color">Selecionar foto <span class="glyphicon glyphicon-camera"></span></button>
      <div class="caption text-center">
        <h4><?php echo $view_user->name; ?></h4> 
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-8">
    <div class="thumbnail">
      <div class="caption">

        <form method="post" action="<?php echo BASE . 'perfil/editar/'; ?>" role="form" accept-charset="utf-8" enctype="multipart/form-data">
          <?php

            $values = [
                'name' => $view_user->name,
                'username' => $view_user->username,
                'email' => $view_user->email
            ];

          ?>
          <div class="form-group">
            <label for="name">Nome <span style="color: red;">*</span></label>
            <input type="text" class="form-control" name="name" value="<?php echo $values['name']; ?>">
          </div>
          <div class="form-group">
            <label for="username">Username <span style="color: red;">*</span></label>
            <input type="text" class="form-control" name="username" value="<?php echo $values['username']; ?>">
          </div>
          <div class="form-group">
            <label for="email">E-mail <span style="color: red;">*</span></label>
            <input type="email" class="form-control" name="email" value="<?php echo $values['email']; ?>">
          </div>
          <!-- <div class="form-group">
            <label for="sexo">Sexo</label>
            <select class="form-control">
              <option>Masculino</option>
              <option>Feminino</option>
            </select>
          </div> -->
          <!-- <div class="form-group">
            <label for="funcao">Função</label>
            <input type="text" class="form-control" id="funcao" placeholder="Administrador ou Funcionário">
          </div> -->
          <hr>
          <div class="form-group">
            <label for="newPass">Nova Senha (Se quiser alterar a existente)</label>
            <input type="password" class="form-control" name="newPass" placeholder="Nova Senha">
          </div>
          <div class="form-group">
            <label for="conNewPass">Confirmar nova senha</label>
            <input type="password" class="form-control" name="conNewPass" placeholder="Confirme sua nova senha">
          </div>
          <!-- <hr>
          <div class="form-group">
            <label for="empresa">Empresa</label>
            <input type="text" class="form-control" id="empresa" placeholder="Nome da Empresa">
          </div>
          <div class="form-group">
            <label for="cargo">Cargo</label>
            <input type="text" class="form-control" id="cargo" placeholder="Cargo na Empresa">
          </div> -->
          <hr>
          <div class="text-right">
            <button type="button" class="btn btn-danger"><span class="fa fa-remove"></span> Cancelar</button>
            <button type="submit" class="btn side-primary-color"><i class="fa fa-check"></i> Atualizar</button>
          </div>
        </form>
      </div>
    </div>
  </div>

</div>