<div class="modal fade" id="modalImport" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><b>Importar</b> planilhas de produtos</h4>
      </div>
      <div class="modal-body">
        <h4>Envie sua planilha para o SIDE</h4>
        <p>Selecione arquivo Excel (.xlsx) com os dados dos seus produtos.</p>
        
        <form action="" method="post" enctype="multipart/form-data">

        <div class="modal-box">
          <input type="file" class="btn side-primary-color" />
          <p>(Até <b>500</b> itens na tabela ou <b>1 mb</b> no tamanho do arquivo)</p>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-success">Enviar</button>

        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->