<div class="modal fade" id="modalCobertura" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Histórico da Cobertura de Estoque</h4>
      </div>
      <div class="modal-body">
        <canvas id="historico-cobertura"></canvas>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn side-primary-color" data-dismiss="modal">OK</button>
  
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
  var ctx = document.getElementById("historico-cobertura");

  var chartGraph = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [
        <?php
          $view_array_indicadores = array_reverse($view_array_indicadores); 
          foreach ($view_array_indicadores as $linha) {
              if ($linha == end($view_array_indicadores)) {
                echo "'".strftime('%b/%Y', strtotime($linha->date))."'";
              }
              else {
                echo "'".strftime('%b/%Y', strtotime($linha->date))."'" . ',';
              }
          }
        ?>
      ],
      datasets: [{
        label: 'Histórico da Cobertura',
        data: [
          <?php 
            foreach ($view_array_indicadores as $linha) {
                if ($linha == end($view_array_indicadores)) {
                  echo number_format($linha->cobertura_estoque, 2);
                }
                else {
                  echo number_format($linha->cobertura_estoque, 2) . ",";
                }
            }
          ?>
        ],
        borderWidth: 3,
        borderColor: 'rgba(0,2,456,0.6)',
        backgroundColor: 'transparent'
      }] 
    },
    options: {
      legend: {
            labels: {
                // This more specific font property overrides the global property
                fontColor: 'black',
                fontSize: 20
            }
        }
    }
  });
</script>