<div class="modal fade" id="modalGiro" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Histórico do Giro de Estoque</h4>
      </div>
      <div class="modal-body">
        <?php if(count($view_array_indicadores_modal) > 1) : ?>
        <div style="" class="text-center">
          <h3><?php echo $view_description; ?></h3>
        </div>
        <canvas id="historico-giro"></canvas>
        <div style="padding-top: 10px;" class="text-center">
          <p><strong>Obs:</strong> <i>Você pode visualizar o histórico do giro de estoque desse produto em até os últimos 10 meses.</i></p>
        </div>
        <?php else : ?>
          <div style="background: #eee; padding: 10px; width: 50%; margin: 0 auto; box-shadow: 0 0 5px #aaa;" class="text-center">
            <h3>Não há registros suficientes para gerar o histórico desse produto</h3>
            <hr style="border-color: #aaa;">
            <h5>Insira dados de outros meses para gerarmos o histórico desse produto.</h5>
          </div>
        <?php endif; ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn side-primary-color" data-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
  var ctx = document.getElementById("historico-giro");

  var chartGraph = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [
        <?php
          $view_array_indicadores_modal = array_reverse($view_array_indicadores_modal); 
          foreach ($view_array_indicadores_modal as $linha) {
              if ($linha == end($view_array_indicadores_modal)) {
                echo "'".strftime('%b/%Y', strtotime($linha->date))."'";
              }
              else {
                echo "'".strftime('%b/%Y', strtotime($linha->date))."'" . ',';
              }
          }
        ?>
      ],
      datasets: [{
        label: 'Histórico do Giro',
        data: [
          <?php
             
            foreach ($view_array_indicadores_modal as $linha) {
                if ($linha == end($view_array_indicadores_modal)) {
                  echo number_format($linha->giro_estoque, 2);
                }
                else {
                  echo number_format($linha->giro_estoque, 2) . ",";
                }
            }
          ?>
        ],
        borderWidth: 3,
        borderColor: 'rgba(0,2,456,0.6)',
        backgroundColor: 'transparent'
      }] 
    },
    options: {
      legend: {
            labels: {
                // This more specific font property overrides the global property
                fontColor: 'black',
                fontSize: 20
            }
        }
    }
  });
</script>
