<div class="breadcrumb-custom">
  <i class="fa fa-check"></i> Seja Bem-vindo <?php echo $view_user->name; ?>!
  <span class="location" style="float: right;">Home</span>
</div>

<?php echo (isset($this->alert) ? $this->alert : ''); ?>

<div class="container">

  <div class="row">

    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <div class="col-sm-2" style="font-size: 20pt; color: red;"><?php if(is_null($view_produtos_abaixo_est_minimo)) : echo 0; else : echo $view_produtos_abaixo_est_minimo; endif; ?></div>
            <div class="col-sm-10" style="font-size: 15pt;">Produtos abaixo do estoque mínimo.</div></p>
        </div>
        <div class="panel-footer text-center">Mais detalhes >></div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <div class="col-sm-2" style="font-size: 20pt; color: green;"><?php if(is_null($view_produtos_prox_ponto_reposicao)) : echo 0; else : echo $view_produtos_prox_ponto_reposicao; endif; ?></div>
            <div class="col-sm-10" style="font-size: 15pt;">Produtos prox. ao ponto de pedido.</div></p>
        </div>
        <div class="panel-footer text-center">Mais detalhes >></div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <div class="col-sm-2" style="font-size: 20pt; color: orange;"><?php if(is_null($view_produtos_abaixo_ponto_reposicao)) : echo 0; else : echo $view_produtos_abaixo_ponto_reposicao; endif; ?></div>
            <div class="col-sm-10" style="font-size: 15pt;">Produtos abaixo do ponto de pedido.</div></p>
        </div>
        <div class="panel-footer text-center">Mais detalhes >></div>
      </div>
    </div>
    
  </div>

  <div class="row">
    <div class="col-sm-12">

      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4><i class="fa fa-warning"></i> Atenção!</h4>
        <hr>
        <ul>
          <li>Para melhores resultados ao utilizar o sistema, mantenha os seus dados de estoque atualizados!</li>
          <li>Para o cálculo de alguns indicadores, certos parâmetros precisam ser informados previamente.</li>
        </ul>
      </div>

    </div>
  </div>

  <div class="row">
    
    <div class="col-sm-7">
      <div class="panel panel-default">
        <div class="panel-heading">Gráfico (Total de vendas p/ mês)</div>
        <div class="panel-body">
          <?php if(!empty($view_valores_vendas)) : ?>
          <div class="alert alert-info" role="alert">
            <h4><i class="fa fa-info-circle"></i> Observação!</h4>
            <ul>
              <li>Verifique o total de vendas nos últimos meses abaixo!</li>
            </ul>
          </div>
          <canvas id="vendas-mes"></canvas>
          <?php else : ?>
          <div class="alert alert-danger" role="alert">
            <h4><i class="fa fa-warning"></i> Atenção!</h4>
            <ul>
              <li>Não há dados registrados para gerar o gráfico de vendas, por favor insira os dados no sistema no menu >> produtos.</li>
            </ul>
          </div>
          <canvas id="vendas-mes"></canvas>
          <?php endif; ?>
        </div>
      </div>
    </div>

    <div class="col-sm-5">
      <div class="panel panel-default">
        <div class="panel-heading">Produtos mais vendidos no mês</div>
        <div class="panel-body">
          <?php if(!empty($view_produtos_mais_vendidos)) : ?>
          <div class="alert alert-info" role="alert">
            <h4><i class="fa fa-info-circle"></i> Observação!</h4>
            <p>Verifique abaixo os produtos que mais venderam no último mês.</p>
          </div>
        </div>
        <table class="table table-condensed table-bordered table-hover">
          <thead>
            <tr>
              <th>Descrição</th>
              <th>Faturamento</th>
            </tr>
          </thead>
          <tbody>
            <?php if (isset($view_produtos_mais_vendidos)) : ?>
              <?php foreach ($view_produtos_mais_vendidos as $linha) : ?>
                <tr>
                  <td><?php echo $linha['descricao']; ?></td>
                  <td><?php echo 'R$ ' . number_format($linha['valores_venda'], 2, ',', '.'); ?></td>
                </tr>
              <?php endforeach; ?>
            <?php endif; ?>
          </tbody>
        </table>
        <?php else : ?>
          <div class="alert alert-danger" role="alert">
            <h4><i class="fa fa-warning"></i> Atenção!</h4>
            <p>Não há dados para ser exibido, por favor insira os dados no sistema no menu >> produtos.</p>
          </div>
        <?php endif; ?>
      </div>
    </div>
  </div>

</div>

<script>
  var ctx = document.getElementById("vendas-mes");

  var chartGraph = new Chart(ctx, {
    type: 'line',
    data: {
      labels: [
        <?php
          $view_datas = array_reverse($view_datas);
          foreach ($view_datas as $linha) {
              if ($linha == end($view_datas)) {
                echo "'".strftime('%b/%Y', strtotime($linha))."'";
              }
              else {
                echo "'".strftime('%b/%Y', strtotime($linha))."'" . ',';
              }
          }
        ?> 
      ],
      datasets: [{
        label: 'Total em vendas por mês',
        data: [
          <?php
            $view_valores_vendas = array_reverse($view_valores_vendas); 
            foreach ($view_valores_vendas as $linha) {
                if ($linha == end($view_valores_vendas)) {
                  echo round($linha);
                }
                else {
                  echo round($linha) . ',';
                }
            }
          ?>
        ],
        borderWidth: 3,
        borderColor: 'rgba(0,2,456,0.6)',
        backgroundColor: 'transparent'
      }] 
    },
    options: {
      legend: {
            labels: {
                // This more specific font property overrides the global property
                fontColor: 'black',
                fontSize: 20
            }
      },
      tooltips: {
            callbacks: {
                label: function(tooltipItem, data) {
                    var label = data.datasets[tooltipItem.datasetIndex].label || '';

                    if (label) {
                        label += ': ';
                    }
                    label += tooltipItem.yLabel.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });;
                    return label;
                }
            }
      },
      scales: {
          yAxes: [{
            scaleLabel: {
              display: true,
              labelString: 'Total de vendas (R$)'
            }
          }],
          xAxes: [{
            scaleLabel: {
              display: true,
              labelString: 'Mês/Ano'
            }
          }]
      }
    }
  });
</script>