<div class="breadcrumb-custom">
  <i class="fa fa-check"></i> Seja Bem-vindo <?php echo $view_user->name; ?>!
  <span class="location" style="float: right;">Home</span>
</div>

<?php echo (isset($this->alert) ? $this->alert : ''); ?>

<div class="container">

  <div class="row">

    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <div class="col-sm-2" style="font-size: 20pt; color: red;"><?php echo $view_produtos_abaixo_est_minimo; ?></div>
            <div class="col-sm-10" style="font-size: 15pt;">Produtos abaixo do estoque mínimo.</div></p>
        </div>
        <div class="panel-footer text-center">Mais detalhes >></div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <div class="col-sm-2" style="font-size: 20pt; color: green;"><?php echo $view_produtos_prox_ponto_reposicao; ?></div>
            <div class="col-sm-10" style="font-size: 15pt;">Produtos prox. ao ponto de pedido.</div></p>
        </div>
        <div class="panel-footer text-center">Mais detalhes >></div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <div class="col-sm-2" style="font-size: 20pt; color: orange;"><?php echo $view_produtos_abaixo_ponto_reposicao; ?></div>
            <div class="col-sm-10" style="font-size: 15pt;">Produtos abaixo do ponto de pedido.</div></p>
        </div>
        <div class="panel-footer text-center">Mais detalhes >></div>
      </div>
    </div>
    
  </div>

  <div class="row">
    <div class="col-sm-12">

      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4>Atenção! <i class="fa fa-warning"></i></h4>
        <hr>
        <ul>
          <li>Para melhores resultados ao utilizar o sistema, mantenha os seus dados de estoque atualizados!</li>
          <li>Para o cálculo de alguns indicadores, certos parâmetros precisam ser informados previamente.</li>
        </ul>
      </div>

    </div>
  </div>

</div>