<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Indicadores
  <span class="location" style="float: right;">Home > Indicadores > Listar </span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>

  <div class="row">
    <div class="col-sm-12">
      <?php if(!empty($view_datas)) : ?>
      <div class="btn-group" data-toggle="tooltip" data-placement="top" title="Selecione o mês para calcular os indicadores!">
        <button type="button" class="btn side-primary-color dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Gerar Indicadores <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" style="overflow-y: scroll; max-height: 60px;">
          <?php foreach($view_datas as $data) : ?>
            <li><a href="<?php $this->printRelativeURL('indicadores', false); ?>/gerarTodosIndicadores/<?php echo strftime('%Y-%m', strtotime($data->data)); ?>"><?php echo utf8_encode(strftime('%B/%Y', strtotime($data->data))); ?></a></li>
          <?php endforeach; ?>
        </ul>
      </div>

      <div class="btn-group" data-toggle="tooltip" data-placement="top" title="Selecione o mês para calcular os indicadores!">
        <button type="button" class="btn side-primary-color dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-th-list"></i> Gerar Curva ABC <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" style="overflow-y: scroll; max-height: 60px;">
          <?php foreach($view_datas as $data) : ?>
            <li><a href="<?php $this->printRelativeURL('indicadores', false); ?>/gerarListaABC/<?php echo strftime('%Y-%m', strtotime($data->data)); ?>"><?php echo utf8_encode(strftime('%B/%Y', strtotime($data->data))); ?></a></li>
          <?php endforeach; ?>
        </ul>
      </div>
    <?php endif; ?>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="table-responsive">
      
      <table class="table table-striped table-condensed table-bordered table-hover table-prod" id="table_indicators">
        <thead>
          <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Unidade</th>
            <th>Giro de Estoque</th>
            <th>Cobertura de Estoque</th>
            <th>Estoque Mínimo</th>
            <th>Ponto de Pedido</th>
            <th>Lote de Reposição</th>
            <th>Período (Mês)</th>
          </tr>
        </thead>
        <tbody>
          <?php 
            if ($view_products) :
              foreach ($view_products as $product) :
          ?>
              <tr>
                <td class="col-sm-1"><?php echo $product['codigo_interno']; ?></td>
                <td class="col-sm-3 text-center"><?php echo $product['descricao']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['unidade']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['giro_estoque']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['cobertura_estoque'] . ' dias'; ?></td>
                <td class="col-sm-1 text-center"><?php if(is_null($product['estoque_minimo'])) : echo "- <i data-toggle='tooltip' data-placement='top' title='Sem parametros suficientes para o cálculo!'>SP</i> -"; else : echo $product['estoque_minimo']; endif; ?></td>
                <td class="col-sm-1 text-center"><?php if(is_null($product['ponto_reposicao'])) : echo "- <i data-toggle='tooltip' data-placement='top' title='Sem parametros suficientes para o cálculo!'>SP</i> -"; else : echo $product['ponto_reposicao']; endif; ?></td>
                <td class="col-sm-1 text-center"><?php if(is_null($product['lote_reposicao'])) : echo "- <i data-toggle='tooltip' data-placement='top' title='Sem parametros suficientes para o cálculo!'>SP</i> -"; else : echo $product['lote_reposicao']; endif; ?></td>
                <td class="col-sm-2 text-center"><?php echo utf8_encode(strftime('%B/%Y', strtotime($product['data']))); ?></td>
              </tr>
          <?php
              endforeach;
            endif;
          ?>
        </tbody>
      </table>  
    </div>
  </div>

</div>