<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Indicadores
  <span class="location" style="float: right;">Home > Indicadores > Listar </span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>

  <div class="row">
    <div class="col-sm-8">
      <div class="btn-group" data-toggle="tooltip" data-placement="top" title="Selecione o mês para calcular os indicadores!">
        <button type="button" class="btn side-primary-color dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Gerar Indicadores <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" style="overflow-y: scroll; max-height: 60px;">
          <?php foreach($view_datas as $data) : ?>
            <li><a href="<?php $this->printRelativeURL('indicadores', false); ?>/gerarTodosIndicadores/<?php echo strftime('%Y-%m-%d', strtotime($data->data)); ?>"><?php echo strftime('%B/%Y', strtotime($data->data)); ?></a></li>
          <?php endforeach; ?>
        </ul>
      </div>
    </div>

    <div class="col-sm-4 pull-right">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Buscar por nome">
        <span class="input-group-btn">
          <button class="btn side-primary-color" type="button"><span class="glyphicon glyphicon-search"></span></button>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>

  <br>

  <div class="row">
    <div class="table-responsive">
      
      <table class="table table-striped table-condensed table-bordered table-hover table-prod">
        <thead>
          <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Unidade</th>
            <th>Giro de Estoque</th>
            <th>Cobertura de Estoque</th>
            <th>Estoque Mínimo</th>
            <th>Ponto de Pedido</th>
            <th>Lote de Reposição</th>
            <th>Período (Mês)</th>
          </tr>
        </thead>
        <tbody>
          <?php 
            if ($view_products) :
              foreach ($view_products as $product) :
          ?>
              <tr>
                <td class="col-sm-1"><?php echo $product['codigo_interno']; ?></td>
                <td class="col-sm-3 text-center"><?php echo $product['descricao']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['unidade']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['giro_estoque']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['cobertura_estoque'] . ' dias'; ?></td>
                <td class="col-sm-1 text-center"><?php if(is_null($product['estoque_minimo'])) : echo "- <i>SP</i> -"; else : echo $product['estoque_minimo']; endif; ?></td>
                <td class="col-sm-1 text-center"><?php if(is_null($product['ponto_reposicao'])) : echo "- <i>SP</i> -"; else : echo $product['ponto_reposicao']; endif; ?></td>
                <td class="col-sm-1 text-center"><?php if(is_null($product['lote_reposicao'])) : echo "- <i>SP</i> -"; else : echo $product['lote_reposicao']; endif; ?></td>
                <td class="col-sm-2 text-center"><?php echo strftime('%B/%Y', strtotime($product['data'])); ?></td>
              </tr>
          <?php
              endforeach;
            endif;
          ?>
        </tbody>
      </table>  
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4 prod-count">
      <p>
        <?php 
          echo 'Mostrando ' . $view_primeiro_produto . ' a ';
          
          if(($view_primeiro_produto + 9) > $view_total_produtos) :
            echo $view_total_produtos;
          else :
            echo ($view_primeiro_produto + 9);
          endif;

          echo ' de um total de ' . $view_total_produtos; 
        ?>
      </p>
    </div>

    <?php if($view_total_paginas > 1) : ?>

    <div class="col-sm-7 pull-right text-right paginacao">
      <nav aria-label="Page navigation">
        <ul class="pagination">

          <?php if($view_anterior > 0) : ?>
            <li>
              <a href="<?php $this->printRelativeURL('indicadores', false); ?>/listar/1" aria-label="Previous">
                <span aria-hidden="true">&laquo; Primeira</span>
              </a>
            </li>
          <?php else : ?>
            <li class="disabled">
                <span aria-hidden="true">&laquo; Primeira</span>
            </li>
          <?php endif; ?>

          <?php if($view_anterior > 0) : ?>
            <li><a href="<?php $this->printRelativeURL('indicadores', false); ?>/listar/<?php echo $view_anterior; ?>"><?php echo $view_anterior; ?></a></li>
          <?php endif; ?>
          
      
          <li class="active"><a href="<?php $this->printRelativeURL('indicadores', false); ?>/listar/<?php echo $view_pagina; ?>"><?php echo $view_pagina; ?></a></li>
          
          <?php if($view_pagina < $view_total_paginas) : ?>
            <li><a href="<?php $this->printRelativeURL('indicadores', false); ?>/listar/<?php echo $view_proximo; ?>"><?php echo $view_proximo; ?></a></li>
            <li>
              <a href="<?php $this->printRelativeURL('indicadores', false); ?>/listar/<?php echo $view_total_paginas; ?>" aria-label="Next">
                <span aria-hidden="true">Última &raquo;</span>
              </a>
            </li>
          <?php else : ?>
            <li class="disabled">
                <span aria-hidden="true">Última &raquo;</span>
            </li>
          <?php endif; ?>

        </ul>
      </nav>
    </div>

    <?php endif; ?>
  </div>

</div>