<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Vendas
  <span class="location" style="float: right;">Home > Vendas > Listar</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>

  <div class="row">
    <div class="col-sm-6">
      <div class="btn-group" role="group">
        <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span> Registrar Venda</a>
      </div>
    </div>

    <div class="col-sm-4 pull-right">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Buscar por descrição...">
        <span class="input-group-btn">
          <button class="btn side-primary-color" type="button"><span class="glyphicon glyphicon-search"></span></button>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>

  <br>

  <div class="row">
    <div class="table-responsive">
      
      <table class="table table-striped table-condensed table-bordered table-prod">
        <thead>
          <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Valor (Unid)</th>
            <th>Quantidade</th>
            <th>Total</th>
            <th>Data</th>
          </tr>
        </thead>
        <tbody>
          <?php 
            if ($view_vendas) :
              foreach ($view_vendas as $venda) :
          ?>
              <tr class="text-center">
                <td class="col-sm-1"><?php $venda['codigo_interno']; ?></td>
                <td class="col-sm-4"><?php echo $venda['description']; ?></td>
                <td class="col-sm-2"><?php echo 'R$ ' . number_format($venda['value'], 2, ',', '.'); ?></td>
                <td class="col-sm-1"><?php echo $venda['quantity']; ?></td>
                <td class="col-sm-2"><?php echo 'R$ ' . number_format($venda['total'], 2, ',', '.'); ?></td>
                <td class="col-sm-2">
                  <?php echo date('d/m/Y', strtotime($venda['date_sell'])) . ' às ' .date('H:i', strtotime($venda['date_sell'])); ?>
                </td>
              </tr>
          <?php
              endforeach;
            endif;
          ?>
        </tbody>
      </table>  
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <p style="
          background: #555;
          color: #fff;
          font-style: italic;
          padding: 5px;
          text-align: center;
          font-size: 10pt;
          border-radius: 5px;
      ">
        <?php 
          echo 'Mostrando ' . $view_primeira_venda . ' a ';
          
          if(($view_primeira_venda + 9) > $view_total_vendas) :
            echo $view_total_vendas;
          else :
            echo ($view_primeira_venda + 9);
          endif;

          echo ' de um total de ' . $view_total_vendas; 
        ?>
      </p>
    </div>

    <?php if($view_total_paginas > 1) : ?>

    <div class="col-sm-7 pull-right text-right paginacao">
      <nav aria-label="Page navigation">
        <ul class="pagination">

          <?php if($view_anterior > 0) : ?>
            <li>
              <a href="<?php $this->printRelativeURL('venda', false); ?>/listar/<?php echo $view_anterior; ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo; Anterior</span>
              </a>
            </li>
          <?php else : ?>
            <li class="disabled">
                <span aria-hidden="true">&laquo; Anterior</span>
            </li>
          <?php endif; ?>

          <?php if($view_anterior > 0) : ?>
            <li><a href="<?php $this->printRelativeURL('venda', false); ?>/listar/<?php echo $view_anterior; ?>"><?php echo $view_anterior; ?></a></li>
          <?php endif; ?>
          
      
          <li class="active"><a href="<?php $this->printRelativeURL('venda', false); ?>/listar/<?php echo $view_pagina; ?>"><?php echo $view_pagina; ?></a></li>
          
          <?php if($view_pagina < $view_total_paginas) : ?>
            <li><a href="<?php $this->printRelativeURL('venda', false); ?>/listar/<?php echo $view_proximo; ?>"><?php echo $view_proximo; ?></a></li>
            <li>
              <a href="<?php $this->printRelativeURL('venda', false); ?>/listar/<?php echo $view_proximo; ?>" aria-label="Next">
                <span aria-hidden="true">Próximo &raquo;</span>
              </a>
            </li>
          <?php else : ?>
            <li class="disabled">
                <span aria-hidden="true">Próximo &raquo;</span>
            </li>
          <?php endif; ?>

        </ul>
      </nav>
    </div>

    <?php endif; ?>
  </div>

</div>