<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Cadastrar produto
  <span class="location" style="float: right;">Home > Produtos > Cadastrar</span>
</div>

<div class="container">

  <div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-warning"></i> Atenção!</h3>
      </div>
      <div class="panel-body">
        <p class="text-center">Todos os campos marcados com <span style="color: red;">*</span> são obrigatórios.</p>
      </div>
  </div>

  <form action="" accept-charset="utf-8" role="form">
    <div class="col-xs-12 container-form">
      <h4>Dados</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-4">
          <label>Nome do produto <span style="color: red;">*</span></label>
          <label data-toggle="tooltip" data-placement="top" title="Informe o nome do produto"><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <input type="text" name="description" class="form-control" required="required">
        </div>
        <div class="form-group col-sm-4 col-md-4">
          <label>Código Interno</label>
          <label><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <input type="number" class="form-control" required="required">
        </div>
        <!-- <div class="form-group col-sm-4 col-md-4">
          <label>Categoria</label>
          <label><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <select class="form-control">
            <option>Alimentos</option>
            <option>Bebidas</option>
            <option>Eletrônicos</option>
            <option>Informática</option>
            <option>Outros</option>
          </select>
        </div> -->
      </div>

      <div class="row">
        <div class="form-group col-sm-4 col-md-4">
          <label>Valor de Custo</label>
          <label><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <input type="text" name="cost" class="form-control real" required="required" placeholder="0,00">
        </div>
        <div class="form-group col-sm-4 col-md-4 col-md-offset-4 col-md-pull-4">
          <label>Valor de Venda <span style="color: red;">*</span></label>
          <label><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <input type="text" name="sell_value" class="form-control real" required="required" placeholder="0,00">
        </div>
      </div>

      <hr>
      
        <h4>Estoque</h4>
      <div class="row">
        <!-- <div class="form-group col-sm-3 col-md-3">
          <label>Movimenta estoque</label>
          <label><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <select class="form-control">
            <option>Não</option>
            <option>Sim</option>
          </select>
        </div> -->
        <div class="form-group col-sm-4">
          <label>Estoque mínimo <span style="color: red;">*</span></label>
          <label><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <input type="number" class="form-control" required="required">
        </div>
        <div class="form-group col-sm-4">
          <label>Estoque máximo</label>
          <label><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <input type="number" class="form-control" required="required">
        </div>
        <div class="form-group col-sm-4">
          <label>Estoque atual</label>
          <label><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <input type="number" class="form-control" required="required">
        </div>
      </div>
      
      <hr>

      <!-- <h4>Fornecedor</h4>

      <div class="row">
        <div class="form-group col-sm-12 col-md-12">
          <label>Vincule fornecedor</label>
          <label data-toggle="tooltip" data-placement="top" title="Vincule um fornecedor ao produto"><span class="glyphicon glyphicon-exclamation-sign"></span></label>
          <select class="form-control">
            <option>Fornecedor 01</option>
            <option>Fornecedor 02</option>
            <option>Fornecedor 03</option>
            <option>Fornecedor 04</option>
            <option>...</option>
          </select>
        </div>
        <div class="col-sm-12 col-md-12">
          <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar novo fornecedor</button>
        </div>
        </div>

        <hr> -->
        
        <div class="col-sm-12 col-md-12 text-right">
          <button type="button" class="btn btn-danger"><span class="fa fa-remove"></span> Cancelar</button>
          <button type="button" class="btn side-primary-color"><span class="fa fa-check"></span> Cadastrar</button>
        </div>

    </div>
  </form>

</div>