<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Produtos
  <span class="location" style="float: right;">Home > Produtos > Listar</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>
  
  <?php $this->partial('modal-import'); ?>

  <div class="row">
    <div class="col-sm-6">
      <div class="btn-group" role="group">
        <a href="<?php $this->printRelativeURL('cadastrarProduto', true); ?>" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar produto</a>
        <div class="btn-group" role="group">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <span class="glyphicon glyphicon-wrench"></span> Mais ações
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><a href="#" data-toggle="modal" data-target="#modalImport">Importar de uma planilha</a></li>
            <li><a href="#">Exportar Produtos</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-sm-4 pull-right">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Buscar por nome">
        <span class="input-group-btn">
          <button class="btn side-primary-color" type="button"><span class="glyphicon glyphicon-search"></span></button>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>

  <br>

  <div class="row">
    <div class="table-responsive">
      
      <table class="table table-striped table-condensed table-bordered table-prod">
        <thead>
          <tr>
            <th>Cód</th>
            <th>Descrição</th>
            <th>Valor Varejo</th>
            <th>Estoque</th>
            <th>Cadastrado em</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <?php 
            if ($view_products) :
              foreach ($view_products as $product) :
          ?>
              <tr>
                <td class="col-sm-1"><?php echo $product->internal_code; ?></td>
                <td class="col-sm-4"><?php echo $product->description; ?></td>
                <td class="col-sm-2 text-center"><?php echo 'R$ ' . number_format($product->value, 2, ',', '.'); ?></td>
                <td class="col-sm-1 text-center"><?php echo $product->est_atual; ?></td>
                <td class="col-sm-2 text-center"><?php echo date('d/m/Y', strtotime($product->data_entrada)) . ' às ' .date('h:i', strtotime($product->data_entrada)); ?></td>
                <td class="col-sm-2">
                  <button type="button" class="btn btn-success btn-xs" data-toggle="tooltip" data-placement="top" title="Visulizar"><span class="glyphicon glyphicon-search"></span></button>
                  <a href="#" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="Editar"><span class="glyphicon glyphicon-edit"></span></a>
                  <button type="button" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" title="Deletar"><span class="glyphicon glyphicon-remove"></span></button>
                  <a href="<?php echo BASE; ?>indicadores/geraIndicador/<?php echo intval($product->id); ?>" class="btn side-primary-color btn-xs" id="prd_01" title="Gerar Indicadores"><i class="fa fa-line-chart"></i></a>
                  <form action="<?php echo BASE . 'venda/venda/'; ?>" method="post" accept-charset="utf-8">
                    <input type="hidden" name="id" value="<?php echo $product->id; ?>">
                    <input type="hidden" name="descricao" value="<?php echo $product->description; ?>">
                    <input type="hidden" name="valor_produto" value="<?php echo $product->value; ?>">
                    <input type="hidden" name="est_atual" value="<?php echo $product->est_atual; ?>">
                    <button type="submit" class="btn btn-warning btn-xs" id="" data-toggle="tooltip" data-placement="top" title="Vender"><i class="fa fa-dollar"></i></button>
                  </form>  

                </td>
              </tr>
          <?php
              endforeach;
            endif;
          ?>
        </tbody>
      </table>  
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <p style="
          background: #555;
          color: #fff;
          font-style: italic;
          padding: 5px;
          text-align: center;
          font-size: 10pt;
          border-radius: 5px;
      ">
        <?php 
          echo 'Mostrando ' . $view_primeiro_produto . ' a ';
          
          if(($view_primeiro_produto + 9) > $view_total_produtos) :
            echo $view_total_produtos;
          else :
            echo ($view_primeiro_produto + 9);
          endif;

          echo ' de um total de ' . $view_total_produtos; 
        ?>
      </p>
    </div>

    <?php if($view_total_paginas > 1) : ?>

    <div class="col-sm-7 pull-right text-right paginacao">
      <nav aria-label="Page navigation">
        <ul class="pagination">

          <?php if($view_anterior > 0) : ?>
            <li>
              <a href="<?php echo BASE; ?>produtos/listar/<?php echo $view_anterior; ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo; Anterior</span>
              </a>
            </li>
          <?php else : ?>
            <li class="disabled">
                <span aria-hidden="true">&laquo; Anterior</span>
            </li>
          <?php endif; ?>

          <?php if($view_anterior > 0) : ?>
            <li><a href="<?php echo BASE; ?>produtos/listar/<?php echo $view_anterior; ?>"><?php echo $view_anterior; ?></a></li>
          <?php endif; ?>
          
      
          <li class="active"><a href="<?php echo BASE; ?>produtos/listar/<?php echo $view_pagina; ?>"><?php echo $view_pagina; ?></a></li>
          
          <?php if($view_pagina < $view_total_paginas) : ?>
            <li><a href="<?php echo BASE; ?>produtos/listar/<?php echo $view_proximo; ?>"><?php echo $view_proximo; ?></a></li>
            <li>
              <a href="<?php echo BASE; ?>produtos/listar/<?php echo $view_proximo; ?>" aria-label="Next">
                <span aria-hidden="true">Próximo &raquo;</span>
              </a>
            </li>
          <?php else : ?>
            <li class="disabled">
                <span aria-hidden="true">Próximo &raquo;</span>
            </li>
          <?php endif; ?>

        </ul>
      </nav>
    </div>

    <?php endif; ?>
  </div>

</div>