<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Produtos
  <span class="location" style="float: right;">Home > Produtos > Listar</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>
  
  <?php $this->partial('modal-import'); ?>

  <div class="row">
    <div class="col-sm-12">
      <div class="btn-group" role="group">
        <a href="<?php $this->printRelativeURL('redirecionarCadastro', true); ?>" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Adicione um produto para o mês atual."><i class="fa fa-plus-circle"></i> <span class="hidden-xs">Adicionar produto</span></a>
        <div class="btn-group" role="group" data-toggle="tooltip" data-placement="top" title="Importe sua planilha para o sistema.">
            <a href="#" class="btn btn-default" data-toggle="modal" data-target="#modalImport"><i class="fa fa-file-excel-o"></i> <span class="hidden-xs">Importar (Planilha)</span></a>
        </div>
      </div>
      <div class="btn-group" data-toggle="tooltip" data-placement="top" title="Selecione o mês para calcular os indicadores!">
        <button type="button" class="btn side-primary-color dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Gerar Indicadores <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" style="overflow-y: scroll; max-height: 60px;">
          <?php foreach($view_datas as $data) : ?>
            <li><a href="<?php $this->printRelativeURL('indicadores', false); ?>/gerarTodosIndicadores/<?php echo strftime('%Y-%m', strtotime($data->data)); ?>"><?php echo strftime('%B/%Y', strtotime($data->data)); ?></a></li>
          <?php endforeach; ?>
        </ul>
      </div>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="table-responsive">
      
      <table class="table table-striped table-condensed table-hover table-prod" id="table_prod">
        <thead>
          <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Unidade</th>
            <th>Quant. vendida</th>
            <th>Estoque</th>
            <th>Cadastrado em</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <?php 
            if ($view_products) :
              foreach ($view_products as $product) :
          ?>
              <tr>
                <td class="col-sm-1 text-center"><?php echo $product['internal_code']; ?></td>
                <td class="col-sm-3 text-center"><?php echo $product['description']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['unity']; ?></td>
                <td class="col-sm-2 text-center"><?php echo $product['quantidade_vendida']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['estoque_atual']; ?></td>
                <td class="col-sm-2 text-center"><?php echo date('d/m/Y', strtotime($product['date_insert'])) . ' às ' .date('H:i', strtotime($product['date_insert'])); ?></td>
                <td class="col-sm-2">
                  <a href="<?php $this->printRelativeURL('produtos', false); ?>/visualizarProduto/<?php echo intval($product['id']); ?>" class="btn btn-success btn-xs" data-toggle="tooltip" data-placement="top" title="Visulizar"><span class="glyphicon glyphicon-search"></span></a>
                  <a href="<?php $this->printRelativeURL('produtos', false); ?>/redirecionarEdicao/<?php echo intval($product['id']); ?>" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="Editar"><span class="glyphicon glyphicon-edit"></span></a>
                  <a href="<?php $this->printRelativeURL('produtos', false); ?>/deletar/<?php echo intval($product['id']); ?>" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" title="Deletar"><span class="glyphicon glyphicon-remove"></span></a>
                  <a href="<?php $this->printRelativeURL('indicadores', false); ?>/geraIndicador/<?php echo intval($product['id']); ?>/<?php echo strftime('%Y-%m', strtotime($view_datas[0]->data)); ?>" class="btn side-primary-color btn-xs" id="prd_01" data-toggle="tooltip" data-placement="top" title="Gerar indicadores do produto"><i class="fa fa-line-chart"></i></a> 
                </td>
              </tr>
          <?php
              endforeach;
            endif;
          ?>
        </tbody>
      </table>  
    </div>
  </div>

</div>