<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Produtos
  <span class="location" style="float: right;">Home > Produtos > Listar</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>
  
  <?php $this->partial('modal-import'); ?>

  <div class="row">
    <div class="col-sm-8">
      <div class="btn-group" role="group">
        <a href="<?php $this->printRelativeURL('cadastrarProduto', true); ?>" class="btn btn-default"><i class="fa fa-plus-circle"></i> Adicionar produto</a>
        <div class="btn-group" role="group">
            <a href="#" class="btn btn-default" data-toggle="modal" data-target="#modalImport"><i class="fa fa-file-excel-o"></i> Importar (Planilha)</a>
        </div>
      </div>
    </div>

    <div class="col-sm-4 pull-right">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Buscar por nome">
        <span class="input-group-btn">
          <button class="btn side-primary-color" type="button"><span class="glyphicon glyphicon-search"></span></button>
        </span>
      </div><!-- /input-group -->
    </div>
  </div>

  <br>

  <div class="row">
    <div class="table-responsive">
      
      <table class="table table-striped table-condensed table-bordered table-hover table-prod">
        <thead style="vertical-align: middle;">
          <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Unidade</th>
            <th>Estoque</th>
            <th>Cadastrado em</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <?php 
            if ($view_products) :
              foreach ($view_products as $product) :
          ?>
              <tr>
                <td class="col-sm-1 text-center"><?php echo $product['internal_code']; ?></td>
                <td class="col-sm-4 text-center"><?php echo $product['description']; ?></td>
                <td class="col-sm-2 text-center"><?php echo $product['unity']; ?></td>
                <td class="col-sm-1 text-center"><?php echo $product['estoque_atual']; ?></td>
                <td class="col-sm-2 text-center"><?php echo date('d/m/Y', strtotime($product['date_insert'])) . ' às ' .date('H:i', strtotime($product['date_insert'])); ?></td>
                <td class="col-sm-2">
                  <button type="button" class="btn btn-success btn-xs" data-toggle="tooltip" data-placement="top" title="Visulizar"><span class="glyphicon glyphicon-search"></span></button>
                  <a href="#" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="Editar"><span class="glyphicon glyphicon-edit"></span></a>
                  <button type="button" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" title="Deletar"><span class="glyphicon glyphicon-remove"></span></button>
                  <a href="<?php $this->printRelativeURL('Indicadores', false); ?>/geraIndicador/<?php echo intval($product['id']); ?>" class="btn side-primary-color btn-xs" id="prd_01" title="Gerar Indicadores"><i class="fa fa-line-chart"></i></a> 
                </td>
              </tr>
          <?php
              endforeach;
            endif;
          ?>
        </tbody>
      </table>  
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <p style="
          background: #555;
          color: #fff;
          font-style: italic;
          padding: 5px;
          text-align: center;
          font-size: 10pt;
          border-radius: 5px;
      ">
        <?php 
          echo 'Mostrando ' . $view_primeiro_produto . ' a ';
          
          if(($view_primeiro_produto + 9) > $view_total_produtos) :
            echo $view_total_produtos;
          else :
            echo ($view_primeiro_produto + 9);
          endif;

          echo ' de um total de ' . $view_total_produtos; 
        ?>
      </p>
    </div>

    <?php if($view_total_paginas > 1) : ?>

    <div class="col-sm-8 text-right paginacao">
      <nav aria-label="Page navigation">
        <ul class="pagination">

          <?php if($view_anterior > 0) : ?>
            <li>
              <a href="<?php $this->printRelativeURL('produtos', false); ?>/listar/<?php echo $view_anterior; ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo; Anterior</span>
              </a>
            </li>
          <?php else : ?>
            <li class="disabled">
                <span aria-hidden="true">&laquo; Anterior</span>
            </li>
          <?php endif; ?>

          <?php if($view_anterior > 0) : ?>
            <li><a href="<?php $this->printRelativeURL('produtos', false); ?>/listar/<?php echo $view_anterior; ?>"><?php echo $view_anterior; ?></a></li>
          <?php endif; ?>
          
      
          <li class="active"><a href="<?php $this->printRelativeURL('produtos', false); ?>/listar/<?php echo $view_pagina; ?>"><?php echo $view_pagina; ?></a></li>
          
          <?php if($view_pagina < $view_total_paginas) : ?>
            <li><a href="<?php $this->printRelativeURL('produtos', false); ?>/listar/<?php echo $view_proximo; ?>"><?php echo $view_proximo; ?></a></li>
            <li>
              <a href="<?php $this->printRelativeURL('produtos', false); ?>/listar/<?php echo $view_proximo; ?>" aria-label="Next">
                <span aria-hidden="true">Próximo &raquo;</span>
              </a>
            </li>
          <?php else : ?>
            <li class="disabled">
                <span aria-hidden="true">Próximo &raquo;</span>
            </li>
          <?php endif; ?>

        </ul>
      </nav>
    </div>

    <?php endif; ?>
  </div>

</div>