<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Importar planilha
  <span class="location" style="float: right;">Home > Produtos > Importar Planilha</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>

  <div class="row">
    <h3>Informe o que é cada coluna da sua planilha...</h3>
    <p>Informe o tipo de conteúdo de cada coluna para que o sistema importe corretamente.</p>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4>Atenção! <i class="fa fa-warning"></i></h4>
      <p>Os valores marcados (*) são obrigatórios para importação. Por favor preencha os valores!</p>
    </div>
    <!-- <select name="ano" id="ano">
        <option>Selecione mês</option>
        <?php

        for ($i = date("Y"); $i >= 2017; $i--) {
           
          if ($i < date("Y")) {
            for ($j=12; $j >= 01; $j--) {
              echo "<option>" . strftime('%B/%Y', strtotime("$j/01/$i")) . "</option>";
            }
          }
          else {
            for ($j=date("m"); $j >= 01; $j--) { 
              echo "<option>" . strftime('%B/%Y', strtotime("$j/01/$i")) . "</option>";
            }
          }
             
        }?>
       </select> -->
  </div>

  <div class="row">
    <div class="table-responsive">

      <table class="table table-striped table-condensed table-hover table-prod"
      		style="border-collapse: collapse; width: auto; overflow-x: auto; display: block; table-layout: fixed;">
        <thead style="display: block;">
        	<tr style="background-color: rgba(0,0,0,0);">
        	  <form action="<?php $this->printRelativeURL('produtos', false); ?>/inserirDadosPlanilha/" method="post" accept-charset="utf-8">

        	  <input type="hidden" name="total_colunas" value="<?php echo $view_colunas; ?>">
        	  <input type="hidden" name="total_linhas" value="<?php echo $view_linhas; ?>">

        	  <?php for ($i=0; $i < $view_colunas; $i++): ?>
        		<td style="min-width: 180px; height: 25px; width: 180px;">
        			<select name="<?php echo 'select'. $i; ?>" id="<?php echo $i; ?>" class="form-control" onclick="optionValue(this.value, this.id)">
        			  <option value="none">Não importar coluna</option>
        			  <option value="descricao">Descrição *</option>
        			  <option value="codigo_interno">Código</option>
        			  <option value="custo">Custo</option>
        			  <option value="valor_venda">Valor de Venda *</option>
        			  <option value="estoque_atual">Estoque *</option>
        			  <option value="estoque_minimo">Est. Mínimo *</option>
        			  <option value="estoque_maximo">Est. Máximo</option>        			  
        			</select>
        		</td>
        	  <?php endfor; ?>       	  	
        	  
        	</tr>
        	<tr>
    	      <?php foreach ($view_titulo as $linha) : ?>
    				<th class="text-center" style="min-width: 180px; height: 30px; width: 180px;">
    					<b><?php echo $linha; ?></b>
    				</th>
    	      <?php endforeach; ?>
			    </tr>
        </thead>
      
      <!-- <table class="table table-striped table-condensed table-bordered table-prod"
      		style="border-collapse: collapse; width: 100%; overflow-x: hidden; display: block;"> -->
        <tbody style="display: inline-block; overflow-x: auto; height: 300px;">
          <?php 
            if ($view_dados) :
              $coluna = 0; ## Setando coluna
              $linhas = 0;
              $matrizOriginal = array();

              foreach ($view_dados as $linha) :
          ?>  
              <tr>
              	<?php while ($coluna < $view_colunas): ?>
                	<td class="text-center" style="padding: 5px; height: 50px; min-height: 50px; column-width: 160px; min-width: 180px; vertical-align: middle; overflow-x: auto;">
		            	<?php echo $linha[$coluna]; ?>
		            	<?php $matrizOriginal[$linhas][$coluna] = $linha[$coluna]; ?>
                	</td>
            	<?php $coluna++; ?>
            	<?php endwhile; ?>
              </tr>
        	<?php $linhas++; ?>
          <?php
          	  if ($coluna == $view_colunas)
          	  	 $coluna = 0; ## Se chegar na ultima coluna zera.
              endforeach;
              $this->session->set('dadosPlanilha', $matrizOriginal); //Criando sessão com array de dados
          ?>
          <?php endif; ?>
        </tbody>
      </table>  
    </div>
  </div>

  <div class="row">
  	<a href="<?php $this->printRelativeURL('listar', true); ?>" class="btn btn-danger">Cancelar</a>
  	<button type="submit" class="btn btn-success">Salvar</button>
  </div>

 </form>
 </div>
 
 <!-- Script de Scrolling da tabela -->
 <script type="text/javascript">
  $(document).ready(function() {
    $('table').on('scroll', function() {
        $("table > *").width($("table").width() + $("table").scrollLeft());
    }); 
    
  });

  function optionValue(opcao, coluna){
    var col = document.getElementsByTagName("select");
    
      for (var i = 0; i < col.length; i++) {
        var e = document.getElementsByTagName("select")[i].value;

        if(coluna != i) {
          if(opcao == e && opcao != "none") {
            swal({
              type: 'warning',
              title: 'Atenção!',
              text: "Já há uma coluna selecionada com esse valor.",
              confirmButtonClass: "btn-warning",
              confirmButtonText: "OK!",
              closeOnConfirm: true
            });

            document.getElementsByTagName("select")[coluna].value = "none";

            $("select[name='select" + i +"']").change(function() {
              $(this).css('background-color','white'),
              $(this).css('color','#555')
            });
          }
        }
        else {
          if (document.getElementsByTagName("select")[coluna].value != "none") {
            $("select[name='select" + i +"']").click(function() {
              $(this).css('background-color','green'),
              $(this).css('color','white'),
              $('option').css('background-color','white'),
              $('option').css('color','#555')
            });   
          }
        }

        if (opcao == 'none') {
          $("select[name='select" + i +"']").click(function() {
            $(this).css('background-color','white'),
            $(this).css('color','#555')
          });
        }
      }

  }
 </script>