<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Importar planilha
  <span class="location" style="float: right;">Home > Produtos > Importar Planilha</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>
  <div class="row">
    <h3>Informe o que é cada coluna da sua planilha...</h3>
    <p>Informe o tipo de conteúdo de cada coluna para que o sistema importe corretamente.</p>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4>Atenção! <i class="fa fa-warning"></i></h4>
      <ul>
        <li>Os valores marcados (*) são obrigatórios para importação. Por favor preencha os valores!</li>
        <li>Selecione o mês referente ao seu arquivo.</li>
      </ul>
      
    </div>
  </div>

  <div class="row">
    <div class="table-responsive">

      <form action="<?php $this->printRelativeURL('produtos', false); ?>/inserirDadosPlanilha/" method="post" accept-charset="utf-8">

        <div class="col-sm-4 col-xs-12 pull-right" style="margin-bottom: 15px;">
          <select name="data" id="data" class="form-control">
            <option value="null">Selecione mês</option>
            <?php
              for ($i = date("Y"); $i >= 2017; $i--) {
                 
                if ($i < date("Y")) {
                  for ($j=12; $j >= 01; $j--) {
                    echo "<option value='" . date("$j/$i") . "'>" . strftime('%B/%Y', strtotime("$j/01/$i")) . "</option>";
                  }
                }
                else {
                  for ($j=date("m"); $j >= 01; $j--) { 
                    echo "<option value='" . date("$j/$i") . "'>" . strftime('%B/%Y', strtotime("$j/01/$i")) . "</option>";
                  }
                }
                   
              }
            ?>
          </select>
        </div>
        <div class="col-sm-12 col-xs-12">
          <table class="table table-striped table-condensed table-hover table-prod"
              style="border-collapse: collapse; width: auto; overflow-x: auto; display: block; table-layout: fixed;">
            <thead style="display: block;">
              <tr style="background-color: rgba(0,0,0,0.3);">

            	  <input type="hidden" name="total_colunas" value="<?php echo $view_colunas; ?>">
            	  <input type="hidden" name="total_linhas" value="<?php echo $view_linhas; ?>">

            	  <?php for ($i=0; $i < $view_colunas; $i++): ?>
            		<td style="min-width: 180px; height: 25px; width: 180px;">
            			<select name="<?php echo 'select'. $i; ?>" id="<?php echo $i; ?>" class="form-control select" onchange="optionValue(this.value, this.id)">
            			  <option value="none">Não importar coluna</option>
            			  <option value="codigo_interno">Código</option>
                    <option value="descricao">Descrição *</option>
                    <option value="unidade">Unidade</option>
                    <option value="custo">Custo</option>
                    <option value="estoque_atual">Estoque *</option>                            
                    <option value="tempo_reposicao">Tempo de Reposição</option>              
                    <option value="demanda_media">Demanda Média</option>              
                    <option value="freq_compra">Frequência de Compras</option>              
                    <option value="quantidade_vendida">Quantidade vendida *</option>              
            			  <option value="total_vendas">Total de vendas</option>       			  
            			</select>
            		</td>
            	  <?php endfor; ?>       	  	
            	  
            	</tr>
            	<!-- <tr>
        	      <?php foreach ($view_titulo as $linha) : ?>
        				<th class="text-center" style="min-width: 180px; height: 30px; width: 180px;">
        					<b><?php echo $linha; ?></b>
        				</th>
        	      <?php endforeach; ?>
      		    </tr> -->
            </thead>
          
            <tbody style="display: inline-block; overflow-x: auto; height: 300px;">
              <?php 
                if ($view_dados) :
                  $coluna = 0; ## Setando coluna
                  $linhas = 0;
                  $matrizOriginal = array();

                  foreach ($view_dados as $linha) :
              ?>  
                  <tr>
                  	<?php while ($coluna < $view_colunas): ?>
                    	<td class="text-center" style="padding: 5px; height: 50px; min-height: 50px; column-width: 160px; min-width: 180px; vertical-align: middle; overflow-x: auto;">
      	            	<?php echo $linha[$coluna]; ?>
      	            	<?php $matrizOriginal[$linhas][$coluna] = $linha[$coluna]; ?>
                    	</td>
                	<?php $coluna++; ?>
                	<?php endwhile; ?>
                  </tr>
            	<?php $linhas++; ?>
              <?php
              	  if ($coluna == $view_colunas)
              	  	 $coluna = 0; ## Se chegar na ultima coluna zera.
                  endforeach;
                  $this->session->set('dadosPlanilha', $matrizOriginal); //Criando sessão com array de dados
              ?>
              <?php endif; ?>
            </tbody>
          </table>  
        </div>
    </div>
  </div>

  <div class="row">
  	<a href="<?php $this->printRelativeURL('listar', true); ?>" class="btn btn-danger">Cancelar</a>
  	<button type="submit" class="btn btn-success">Salvar</button>
  </div>

 </form>
 </div>
 
 <!-- Script de Scrolling da tabela -->
 <script type="text/javascript">
  $(document).ready(function() {
    $('table').on('scroll', function() {
        $("table > *").width($("table").width() + $("table").scrollLeft());
    }); 
    
  });

  function optionValue(opcao, coluna){
    var col = document.getElementsByClassName("select");
    
      for (var i = 0; i < col.length; i++) {
        var e = document.getElementsByClassName("select")[i].value;

        if(coluna != i) {
          if(opcao == e) {
            swal({
              type: 'warning',
              title: 'Atenção!',
              text: "Já há uma coluna selecionada com esse valor.",
              confirmButtonClass: "btn-warning",
              confirmButtonText: "OK!",
              closeOnConfirm: true
            });

            document.getElementsByClassName("select")[coluna].value = "none";
          }
        }
      }

  }
 </script>