<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Produtos
  <span class="location" style="float: right;">Home > Produtos > Planilha</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>

  <div class="row">
    <div class="table-responsive">
      
      <table class="table table-striped table-condensed table-bordered table-prod">
        <thead>
        	<tr>
	          <?php foreach ($view_titulo as $linha) : ?>
				<td><?php echo $linha; ?></td>
	          <?php endforeach; ?>
			</tr>
        </thead>
        <tbody>
          <?php 
            if ($view_dados) :
              $coluna = 0;
              
              foreach ($view_dados as $linha) :
          ?>
              <tr>
              	<?php while ($coluna < $view_colunas): ?>
                <td><?php echo $linha[$coluna]; ?></td>
            	<?php $coluna++; endwhile; ?>
              </tr>
          <?php
          	  if ($coluna == $view_colunas)
          	  	 $coluna = 0;
              endforeach;
            endif;
          ?>
        </tbody>
      </table>  
    </div>
  </div>

 </div>