<div class="breadcrumb-custom">
  <i class="fa fa-barcode"></i> Visualizar Produto
  <span class="location" style="float: right;">Home > Produtos > Visualizar</span>
</div>

<div class="container">

  <?php echo (isset($this->alert) ? $this->alert : ''); ?>

  <?php $this->partial('modal-giroestoque-grafico', [
  	'array_indicadores' => $view_indicadores,
  	'array_indicadores_modal' => $view_indicadores_modal,
  	'description' => $view_produto->description
  ]); ?>

  <?php $this->partial('modal-coberturaestoque-grafico', [
  	'array_indicadores' => $view_indicadores,
  	'array_indicadores_modal' => $view_indicadores_modal,
  	'description' => $view_produto->description
  ]); ?>

  <div class="row">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title"><?php echo $view_produto->description; ?></h3>
	  </div>
	  <div class="panel-body">

	  	<div class="alert alert-info alert-dismissible" role="alert">
	  	  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  	  <h4><i class="fa fa-info-circle"></i> Observação!</h4>
	  	  <ul>
	  	    <li>Os dados dos parâmetros e dos indicadores abaixo são referentes ao mês mais atual cadastrado no sistema.</li>
	  	  </ul>
	  	</div>
	  	
	  	<div class="page-header">
	  	  <h3><i class="fa fa-cube"></i> Dados</h3>
	  	</div>
	    <ul style="font-size: 13pt; line-height: 40px;">
	    	<li><strong>Código: </strong><?php echo $view_produto->internal_code; ?></li>
	    	<li><strong>Descrição: </strong><?php echo $view_produto->description; ?></li>
	    	<li><strong>Unidade: </strong><?php echo $view_produto->unity; ?></li>
	    </ul>

	    <div class="page-header">
	  	  <h3><i class="fa fa-cubes"></i> Parâmetros</h3>
	  	</div>

	  	<ul style="font-size: 13pt; line-height: 40px;">
	    	<li><strong>Estoque Atual: </strong><?php echo $view_parametros->estoque_atual; ?></li>
	    	<li><strong>Preço (Unidade): </strong><?php if(!is_null($view_parametros->total_vendas)) : echo 'R$ ' . number_format($view_parametros->total_vendas / $view_parametros->quantidade_vendida, 2, ',', '.'); else: echo "<em>Alguns parâmetros não foram informados.</em>"; endif; ?></li>
	    	<li><strong>Custo: </strong><?php if(is_null($view_parametros->custo)) : echo "<em>Sem registros.</em>"; else : echo $view_parametros->custo; endif; ?></li>
	    	<li><strong>Tempo de reposição: </strong><?php if(is_null($view_parametros->tempo_reposicao)) : echo "<em>Sem registros.</em>"; else : echo $view_parametros->tempo_reposicao . ' dias.'; endif; ?></li>
	    	<li><strong>Quandidade vendida no mês: </strong><?php echo $view_parametros->quantidade_vendida . " $view_produto->unity"; ?></li>
	    	<li><strong>Total em vendas no mês: </strong><?php if(is_null($view_parametros->total_vendas)) : echo "<em>Sem registros</em>"; else : echo 'R$ ' . number_format($view_parametros->total_vendas, 2, ',', '.'); endif; ?></li>
	    	<li><strong>Frequência de compras por mês: </strong><?php if(is_null($view_parametros->freq_compra)) : echo "<em>Sem registros</em>"; else : echo $view_parametros->freq_compra; endif; ?></li>
	  	</ul>
	  	
	  	<div class="page-header">
	  	  <h3><i class="fa fa-line-chart"></i> Indicadores</h3>
	  	</div>
	  	<?php if(!empty($view_indicadores)) : ?>
	  	<ul style="font-size: 13pt; line-height: 40px;">
	    	<li><strong>Estoque Mínimo: </strong><?php if(is_null($view_indicadores[0]->estoque_minimo)) : echo '<em>Alguns parâmetros não foram informados.</em>'; else : echo $view_indicadores[0]->estoque_minimo . ' ' . $view_produto->unity; endif; ?></li>
	    	<li><strong>Ponto de Reposição: </strong><?php if(is_null($view_indicadores[0]->ponto_reposicao)) : echo '<em>Alguns parâmetros não foram informados.</em>'; else : echo $view_indicadores[0]->ponto_reposicao . ' ' . $view_produto->unity; endif; ?></li>
	    	<li><strong>Lote de Reposição: </strong><?php if(is_null($view_indicadores[0]->lote_reposicao)) : echo '<em>Alguns parâmetros não foram informados.</em>'; else : echo $view_indicadores[0]->lote_reposicao . ' ' . $view_produto->unity; endif; ?></li>

	    	<li><strong>Giro de Estoque: </strong><?php echo $view_indicadores[0]->giro_estoque; ?> <span data-toggle="tooltip" data-placement="right" title="Pressione para visualizar o histórico do giro de estoque do produto"><button type="button" class="btn side-primary-color" data-toggle="modal" data-target="#modalGiro"><i class="fa fa-history"></i> Histórico</button></span></li>
	    	<li><strong>Cobertura de Estoque: </strong><?php echo $view_indicadores[0]->cobertura_estoque . ' dias.'; ?> <span data-toggle="tooltip" data-placement="right" title="Pressione para visualizar o histórico da cobertura de estoque do produto"><button type="button" class="btn side-primary-color" data-toggle="modal" data-target="#modalCobertura"><i class="fa fa-history"></i> Histórico</button></span></li>
	    </ul>
	    <?php else : ?>
		<div style="background: #eee; padding: 10px; width: 50%; margin: 0 auto; box-shadow: 0 0 5px #aaa;" class="text-center">
			<h3>Você ainda não gerou os indicadores desse produto.</h3>
			<hr style="border-color: #aaa;">
			<h5>Pressione o botão abaixo para gerar os indicadores.</h5>
			<a href="<?php $this->printRelativeURL('indicadores', false); ?>/geraIndicador/<?php echo intval($view_produto->id); ?>/<?php echo strftime('%Y-%m', strtotime($view_parametros->date)); ?>" class="btn side-primary-color"><i class="fa fa-line-chart"></i> Gerar indicadores</a>
		</div>
		<?php endif; ?>	  	
	  </div>
	</div>
  </div>

</div>