<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?php echo $view_title; ?></title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>login.css">
    <link rel="shortcut icon" href="<?php echo IMG; ?>icons/favicon.ico" type="image/x-icon">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php
    echo $add_css;
    echo $add_js;
    ?>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="internal-container">
          
          <?php echo (isset($this->alert) ? $this->alert : ''); ?>

          <div class="col-sm-8 box-mark">
            <img src="<?php echo IMG; ?>logo-side.png" alt="Logomarca SIDE" class="img-responsive img-side">
            <h4 class="text-center">"Tenha um maior controle do seu estoque com os indicadores mais aprimorados do SIDE"</h4>
          </div>

          <div class="col-sm-4">
            <div  id="box-login">
              <p class="text-center hidden-xs">Faça Login e visualize a situação do seu estoque.</p>
              <div class="mini-box">
                <form method="post" action="<?php echo BASE; ?>login/logar/">
                  <div class="form-group">
                    <label for="user_login">Username</label>
                    <input type="text" name="username" class="form-control" id="user_login" placeholder="">
                  </div>
                  <div class="form-group">
                    <label for="pass_login">Senha</label>
                    <input type="password" name="password" class="form-control" id="pass_login" placeholder="">
                  </div>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox"> Lembrar dados
                    </label>
                  </div>
                  <button type="submit" class="btn btn-default btn-block">Entrar</button>
                </form>
              </div>
              <div class="mini-box">
                <p class="text-center">Ainda não tem uma conta? <a href="<?php echo BASE . 'cadastro'; ?>" class="btn btn-default">Cadastre-se</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
    <script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
  </body>
</html>