<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?php echo $view_title; ?></title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>login.css">
    <link rel="shortcut icon" href="<?php echo IMG; ?>icons/favicon.ico" type="image/x-icon">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php
    echo $add_css;
    echo $add_js;
    ?>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-8">
          <img src="<?php echo IMG; ?>logo-side.png" class="img-responsive img-side"> 
          <h4 class="text-center">Tenha um maior controle dos seu estoque com os indicadores mais aprimorados do SIDE</h4>
        </div>  
        <div class="col-sm-4">
          
          <div  id="box-login">
            <p class="text-center hidden-xs">Faça Login e visualize a situação do seu estoque.</p>
            <div class="mini-box">
              <form>
                <div class="form-group">
                  <label for="exampleInputEmail1">E-mail</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Lembrar dados
                  </label>
                </div>
                <button type="submit" class="btn btn-default btn-block">Login</button>
              </form>
            </div>
            <div class="mini-box">
              <h5 class="text-center">Ainda não tem uma conta? <button type="button" class="btn btn-default">Cadastre-se</button></h5>
            </div>
          </div>

        </div>
      </div>
    </div>

    <script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
    <script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
  </body>
</html>