    <footer>
      <div class="footer-internal"> 
        <h4 class="text-center">&copy; 2018 - <i> SIDE</i> </h4>
      </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js"></script>
    <script>
        $(document).ready(function(){
          $('.real').mask('000.000.000.000.000,00', {reverse: true});
        });
    </script>
  </body>
</html>