    <footer>
      <div class="footer-internal"> 
        <h4 class="text-center">&copy; 2018 - <i> SIDE</i> </h4>
      </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>
  </body>
</html>