    <footer>
      <div class="footer-internal"> 
        <h4 class="text-center">&copy; 2017 - <i>Lucas S. Oliveira</i> </h4>
      </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/index.js"></script>
  </body>
</html>