<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?php echo $view_title; ?></title>

    <link rel="shortcut icon" href="<?php echo IMG; ?>icons/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap-sweetalert/dist/sweetalert.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>responsive.css" type="text/css">

    <script src="<?php echo BOWER; ?>/chart.js/dist/Chart.min.js"></script>
        
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <?php
    echo $add_css;
    echo $add_js;
    ?>
  </head>
  <body>
       <div id="navbar-wrapper">
        <header>
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php $this->printRelativeURL('home', false); ?>">
                          SIDE
                        </a>
                    </div>
                    <div id="navbar-collapse" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a id="notifications" href="#" class="" data-toggle="dropdown">
                                    <i class="fa fa-bell"></i> <span class="title-main-bar">Notificações</span>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a id="help" href="#" class="" data-toggle="dropdown">
                                    <i class="fa fa-question-circle"></i> <span class="title-main-bar">Ajuda</span>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a id="settings" href="#" class="" data-toggle="dropdown">
                                    <i class="fa fa-cogs"></i> <span class="title-main-bar">Configurações</span>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a id="user-profile" href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="" class="img-responsive img-thumbnail img-circle"> <?php echo $view_user->name; ?></a>
                                <ul class="dropdown-menu dropdown-block" role="menu">
                                    <li><a href="<?php $this->printRelativeURL('perfil', false); ?>/editar">Editar perfil</a></li>
                                    <li><a href="#">Configurações</a></li>
                                    <li><a href="<?php $this->printRelativeURL('login', false); ?>/sair">Sair</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    </div>
    <div id="wrapper">
        <div id="sidebar-wrapper">
            <aside id="sidebar">
                <ul id="sidemenu" class="sidebar-nav">
                    <li>
                        <a href="<?php $this->printRelativeURL('home', false); ?>">
                            <span class="sidebar-icon"><i class="fa fa-home"></i></span>
                            <span class="sidebar-title">Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php $this->printRelativeURL('produtos', false); ?>/listar/1/">
                            <span class="sidebar-icon"><i class="fa fa-barcode"></i></span>
                            <span class="sidebar-title">Produtos</span>
                        </a>
                        <!-- <a class="accordion-toggle collapsed toggle-switch" data-toggle="collapse" href="#submenu-3">
                            <span class="sidebar-icon"><i class="fa fa-barcode"></i></span>
                            <span class="sidebar-title">Produtos</span>
                            <b class="caret"></b>
                        </a>
                        <ul id="submenu-3" class="panel-collapse collapse panel-switch" role="menu">
                            <li><a href="<?php $this->printRelativeURL('produtos', false); ?>"><i class="fa fa-caret-right"></i>Gerenciar Produtos</a></li>
                        </ul> -->
                    </li>
                    <li>
                        <a href="<?php $this->printRelativeURL('indicadores', false); ?>">
                            <span class="sidebar-icon"><i class="fa fa-line-chart"></i></span>
                            <span class="sidebar-title">Indicadores</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="sidebar-icon"><i class="fa fa-clipboard"></i></span>
                            <span class="sidebar-title">Relatórios</span>
                        </a>
                    </li>
                </ul>
            </aside>            
        </div>
        <main id="page-content-wrapper" role="main">
        </main>
    </div>